import { prisma } from "../../../config/prisma.js";

export class ReportsService {
  // Aggregate stats across all modules using Prisma, support college/hostel filtering
  static async getSummaryStats(hostelId = null) {
    const filter = hostelId ? Number(hostelId) : null;

    let adminsQuery = { role: { name: "admin" } };
    let hostelsQuery = {};
    let studentsQuery = {};

    if (filter) {
      adminsQuery.hostelId = filter;
      hostelsQuery.id = filter;
      studentsQuery.user = { hostelId: filter };
    }

    // Check if library and inventory modules are enabled for the filtered college/hostel
    let showLibrary = true;
    let showInventory = true;

    if (filter) {
      const hostel = await prisma.hostel.findUnique({
        where: { id: filter },
        select: { hasLibrary: true, hasInventory: true }
      });
      if (hostel) {
        showLibrary = hostel.hasLibrary;
        showInventory = hostel.hasInventory;
      } else {
        showLibrary = false;
        showInventory = false;
      }
    }

    const [
      adminsCount,
      hostelsCount,
      studentsCount,
      booksCount,
      activeIssuesCount,
      inventoryItemsCount,
      pendingRequestsCount,
      collegesList
    ] = await Promise.all([
      // 1. Admins (Count users having the role name 'admin')
      prisma.user.count({ where: adminsQuery }),
      // 2. Hostels (Count total hostels)
      prisma.hostel.count({ where: hostelsQuery }),
      // 3. Students (Count total students)
      prisma.student.count({ where: studentsQuery }),
      // 4. Library Books (Total books and active issues)
      showLibrary ? prisma.book.count() : 0,
      showLibrary ? prisma.bookIssue.count({ where: { returnDate: null } }) : 0,
      // 5. Inventory Items (Total items and pending requests)
      showInventory ? prisma.inventoryItem.count() : 0,
      showInventory ? prisma.inventoryRequest.count({ where: { status: "pending" } }) : 0,
      // 6. Fetch all colleges/hostels for the table & filter dropdown
      prisma.hostel.findMany({
        select: {
          id: true,
          name: true,
          status: true,
          hasHostel: true,
          hasLibrary: true,
          hasInventory: true,
          createdAt: true
        }
      })
    ]);

    return {
      admins: adminsCount,
      hostels: hostelsCount,
      students: studentsCount,
      library: {
        books: booksCount,
        activeIssues: activeIssuesCount
      },
      inventory: {
        items: inventoryItemsCount,
        pendingRequests: pendingRequestsCount
      },
      colleges: collegesList
    };
  }

  // Compile stats and format them into a downloadable CSV
  static async generateCsvReport(user, hostelId = null) {
    const stats = await this.getSummaryStats(hostelId);
    let filterName = "All Colleges";
    if (hostelId) {
      const selected = stats.colleges.find(c => c.id === Number(hostelId));
      if (selected) filterName = selected.name;
    }

    const csvRows = [
      ["Report Type", "System Summary Report"],
      ["Filter Applied", filterName],
      ["Generated At", new Date().toISOString()],
      ["Generated By", user.name || user.email],
      [],
      ["Module", "Metric", "Value"],
      ["Users", "Total Administrators", stats.admins],
      ["Hostels", "Total Hostels", stats.hostels],
      ["Students", "Total Students", stats.students],
      ["Library", "Total Books", stats.library.books],
      ["Library", "Active Book Issues", stats.library.activeIssues],
      ["Inventory", "Total Items", stats.inventory.items],
      ["Inventory", "Pending Requests", stats.inventory.pendingRequests]
    ];

    // Escape values and join with commas
    return csvRows
      .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(","))
      .join("\n");
  }
}
